'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import OwnerShell from '@/components/pos/OwnerShell';
import WorkspaceLoader from '@/components/pos/WorkspaceLoader';
import { formatINR, getCurrentOrganization, type CurrentOrganization } from '@/lib/pos';
import { posText } from '@/lib/pos-i18n';
import { getSupabaseBrowserClient } from '@/lib/supabase';

type RangeKey='7'|'30'|'90';
type ReportData={summary:{billCount:number;sales:number;collected:number;due:number;averageBill:number};paymentBreakdown:Array<{method:string;amount:number}>;topProducts:Array<{name:string;quantity:number;sales:number}>;dailySales:Array<{date:string;sales:number;bills:number}>;staffSales:Array<{name:string;sales:number;bills:number}>;lowStock:Array<{id:string;name:string;stock:number;threshold:number;unit:string}>};
type GstData={summary:{invoiceCount:number;grossSales:number;taxableSales:number;cgst:number;sgst:number;igst:number;totalTax:number};rateBreakdown:Array<{rate:number;taxable:number;cgst:number;sgst:number;igst:number;totalTax:number;gross:number}>};
const emptyReport:ReportData={summary:{billCount:0,sales:0,collected:0,due:0,averageBill:0},paymentBreakdown:[],topProducts:[],dailySales:[],staffSales:[],lowStock:[]};
const emptyGst:GstData={summary:{invoiceCount:0,grossSales:0,taxableSales:0,cgst:0,sgst:0,igst:0,totalTax:0},rateBreakdown:[]};

export default function OwnerReportsPage(){
  const router=useRouter();const[org,setOrg]=useState<CurrentOrganization|null>(null);const[range,setRange]=useState<RangeKey>('30');const[data,setData]=useState<ReportData>(emptyReport);const[gst,setGst]=useState<GstData>(emptyGst);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{getCurrentOrganization().then(current=>{if(!current)return router.replace('/auth/login');if(current.role!=='OWNER')return router.replace('/staff');setOrg(current);}).catch(err=>setError(err instanceof Error?err.message:'Could not load reports.'));},[router]);
  useEffect(()=>{if(!org)return;async function load(){setLoading(true);setError('');const days=Number(range);const to=new Date();const from=new Date(to.getTime()-days*86400000);const supabase=getSupabaseBrowserClient();const[reportResult,gstResult]=await Promise.all([supabase.rpc('owner_report_summary',{p_organization_id:org!.organizationId,p_from:from.toISOString(),p_to:to.toISOString()}),supabase.rpc('owner_gst_report_summary',{p_organization_id:org!.organizationId,p_from:from.toISOString(),p_to:to.toISOString()})]);if(reportResult.error||gstResult.error)setError(reportResult.error?.message||gstResult.error?.message||'Could not load report.');else{setData((reportResult.data??emptyReport) as ReportData);setGst((gstResult.data??emptyGst) as GstData);}setLoading(false);}void load();},[org,range]);
  const maxDaily=useMemo(()=>Math.max(1,...data.dailySales.map(d=>Number(d.sales))),[data.dailySales]);
  if(!org)return <WorkspaceLoader/>;const t=posText(org.preferredLanguage);
  return <OwnerShell businessName={org.organizationName} language={org.preferredLanguage}>
    <div className="content-head pos-page-head"><div><span className="page-kicker">{t.reportsKicker}</span><h1>{t.reportsTitle}</h1><p>{t.reportsSub}</p></div><div className="report-range">{(['7','30','90'] as RangeKey[]).map(value=><button key={value} className={range===value?'active':''} onClick={()=>setRange(value)}>{value} {t.days}</button>)}</div></div>{error&&<div className="form-error">{error}</div>}
    <div className="report-stat-grid"><article className="card report-stat"><span>{t.sales}</span><strong>{formatINR(data.summary.sales)}</strong><small>{loading?t.refreshing:`${data.summary.billCount} ${t.invoices.toLowerCase()}`}</small></article><article className="card report-stat"><span>{t.collected}</span><strong>{formatINR(data.summary.collected)}</strong><small>{t.moneyReceived}</small></article><article className="card report-stat"><span>{t.due}</span><strong>{formatINR(data.summary.due)}</strong><small>{t.dueInRange}</small></article><article className="card report-stat"><span>{t.averageBill}</span><strong>{formatINR(data.summary.averageBill)}</strong><small>{t.averageInvoiceValue}</small></article></div>
    <section className="card gst-report-card"><div className="section-head"><div><span className="page-kicker">{t.gstSummary}</span><h2>{t.taxView}</h2><p>{t.cancelledExcluded}</p></div><div className="gst-total-chip"><span>{t.totalGst}</span><strong>{formatINR(gst.summary.totalTax)}</strong></div></div><div className="gst-stat-grid"><div><span>{t.taxableSales}</span><strong>{formatINR(gst.summary.taxableSales)}</strong></div><div><span>CGST</span><strong>{formatINR(gst.summary.cgst)}</strong></div><div><span>SGST</span><strong>{formatINR(gst.summary.sgst)}</strong></div><div><span>IGST</span><strong>{formatINR(gst.summary.igst)}</strong></div></div>{gst.rateBreakdown.length>0&&<div className="data-table-wrap gst-table-wrap"><table className="data-table"><thead><tr><th>{t.gstRate}</th><th>{t.taxable}</th><th>CGST</th><th>SGST</th><th>IGST</th><th>{t.totalTax}</th></tr></thead><tbody>{gst.rateBreakdown.map(row=><tr key={String(row.rate)}><td><strong>{Number(row.rate)}%</strong></td><td>{formatINR(row.taxable)}</td><td>{formatINR(row.cgst)}</td><td>{formatINR(row.sgst)}</td><td>{formatINR(row.igst)}</td><td><strong>{formatINR(row.totalTax)}</strong></td></tr>)}</tbody></table></div>}</section>
    <div className="report-grid">
      <section className="card report-panel report-wide"><div className="section-head"><div><span className="page-kicker">{t.salesTrend}</span><h2>{t.dailySales}</h2></div></div>{data.dailySales.length===0?<div className="empty-state">{t.noSalesPeriod}</div>:<div className="sales-bars">{data.dailySales.map(day=><div className="sales-bar-row" key={day.date}><span>{new Date(`${day.date}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</span><div className="sales-bar-track"><i style={{width:`${Math.max(3,(Number(day.sales)/maxDaily)*100)}%`}}/></div><strong>{formatINR(day.sales)}</strong></div>)}</div>}</section>
      <section className="card report-panel"><div className="section-head"><div><span className="page-kicker">{t.payments}</span><h2>{t.paymentMix}</h2></div></div>{data.paymentBreakdown.length===0?<div className="empty-state">{t.noPaymentData}</div>:<div className="metric-list">{data.paymentBreakdown.map(item=><div key={item.method}><span>{item.method}</span><strong>{formatINR(item.amount)}</strong></div>)}</div>}</section>
      <section className="card report-panel"><div className="section-head"><div><span className="page-kicker">{t.productsKicker}</span><h2>{t.topSellers}</h2></div></div>{data.topProducts.length===0?<div className="empty-state">{t.noProductSales}</div>:<div className="metric-list ranked">{data.topProducts.map((item,index)=><div key={`${item.name}-${index}`}><span><b>{index+1}</b>{item.name}<small>{Number(item.quantity)} {t.sold}</small></span><strong>{formatINR(item.sales)}</strong></div>)}</div>}</section>
      <section className="card report-panel"><div className="section-head"><div><span className="page-kicker">{t.staffKicker}</span><h2>{t.staffCreatedBills}</h2></div></div>{data.staffSales.length===0?<div className="empty-state">{t.noStaffBills}</div>:<div className="metric-list">{data.staffSales.map(item=><div key={item.name}><span>{item.name}<small>{item.bills} {t.invoices.toLowerCase()}</small></span><strong>{formatINR(item.sales)}</strong></div>)}</div>}</section>
      <section className="card report-panel"><div className="section-head"><div><span className="page-kicker">{t.stock.toUpperCase()}</span><h2>{t.needsAttention}</h2></div><button className="btn" onClick={()=>router.push('/owner/inventory')}>{t.inventory}</button></div>{data.lowStock.length===0?<div className="empty-state">{t.stockHealthy}</div>:<div className="metric-list">{data.lowStock.map(item=><div key={item.id}><span>{item.name}<small>{t.alertAt} {Number(item.threshold)} {item.unit}</small></span><strong className="stock-low">{Number(item.stock)} {item.unit}</strong></div>)}</div>}</section>
    </div>
  </OwnerShell>;
}
