'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import OwnerShell from '@/components/pos/OwnerShell';
import WorkspaceLoader from '@/components/pos/WorkspaceLoader';
import { formatDateTime, getCurrentOrganization, type CurrentOrganization } from '@/lib/pos';
import { posText } from '@/lib/pos-i18n';
import { getSupabaseBrowserClient } from '@/lib/supabase';

type Product={id:string;name:string;sku:string|null;barcode:string|null;stock:number;unit:string;low_stock_threshold:number};
type Movement={id:string;product_id:string;movement_type:string;quantity_change:number;stock_after:number;note:string|null;created_at:string;products:{name:string}|null};
export default function OwnerInventoryPage(){
  const router=useRouter();const[org,setOrg]=useState<CurrentOrganization|null>(null);const[products,setProducts]=useState<Product[]>([]);const[movements,setMovements]=useState<Movement[]>([]);const[query,setQuery]=useState('');const[selectedId,setSelectedId]=useState('');const[mode,setMode]=useState<'IN'|'OUT'>('IN');const[quantity,setQuantity]=useState('');const[note,setNote]=useState('');const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
  async function load(organizationId:string){const supabase=getSupabaseBrowserClient();const[p,m]=await Promise.all([supabase.from('products').select('id,name,sku,barcode,stock,unit,low_stock_threshold').eq('organization_id',organizationId).eq('active',true).is('deleted_at',null).order('name').limit(500),supabase.from('inventory_movements').select('id,product_id,movement_type,quantity_change,stock_after,note,created_at,products(name)').eq('organization_id',organizationId).order('created_at',{ascending:false}).limit(100)]);if(p.error)throw p.error;if(m.error)throw m.error;setProducts((p.data??[]) as Product[]);setMovements((m.data??[]) as unknown as Movement[]);}
  useEffect(()=>{getCurrentOrganization().then(async current=>{if(!current)return router.replace('/auth/login');if(current.role!=='OWNER')return router.replace('/staff');setOrg(current);await load(current.organizationId);}).catch(err=>setError(err instanceof Error?err.message:'Could not load inventory.'));},[router]);
  const filtered=useMemo(()=>{const text=query.trim().toLowerCase();return products.filter(p=>!text||[p.name,p.sku,p.barcode].some(v=>String(v??'').toLowerCase().includes(text)));},[products,query]);const selected=products.find(p=>p.id===selectedId)||null;const t=posText(org?.preferredLanguage??'en');
  async function adjust(event:FormEvent){event.preventDefault();if(!org||!selectedId)return;const amount=Number(quantity);if(!Number.isFinite(amount)||amount<=0)return setError(org.preferredLanguage==='hi'?'सही मात्रा दर्ज करें।':org.preferredLanguage==='hinglish'?'Valid quantity enter karo.':'Enter a valid quantity.');setSaving(true);setError('');setSuccess('');const change=mode==='IN'?amount:-amount;const{error:rpcError}=await getSupabaseBrowserClient().rpc('adjust_product_stock',{p_organization_id:org.organizationId,p_product_id:selectedId,p_quantity_change:change,p_note:note||null});setSaving(false);if(rpcError)return setError(rpcError.message);setSuccess(mode==='IN'?(org.preferredLanguage==='hi'?'स्टॉक सफलतापूर्वक जोड़ दिया गया।':org.preferredLanguage==='hinglish'?'Stock successfully add ho gaya.':'Stock added successfully.'):(org.preferredLanguage==='hi'?'स्टॉक सफलतापूर्वक घटा दिया गया।':org.preferredLanguage==='hinglish'?'Stock successfully remove ho gaya.':'Stock removed successfully.'));setQuantity('');setNote('');await load(org.organizationId);}
  if(!org)return <WorkspaceLoader/>;
  return <OwnerShell businessName={org.organizationName} language={org.preferredLanguage}>
    <div className="content-head pos-page-head"><div><span className="page-kicker">{t.inventoryKicker}</span><h1>{t.inventoryTitle}</h1><p>{t.inventorySub}</p></div></div>{error&&<div className="form-error">{error}</div>}{success&&<div className="form-success">{success}</div>}
    <div className="inventory-layout"><section className="card pos-panel"><div className="list-toolbar"><input className="input search-input" placeholder={t.searchProductSkuBarcode} value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} {t.products.toLowerCase()}</span></div><div className="inventory-product-list">{filtered.map(product=>{const low=Number(product.stock)<=Number(product.low_stock_threshold);return <button key={product.id} className={`inventory-product ${selectedId===product.id?'active':''}`} onClick={()=>setSelectedId(product.id)}><span><strong>{product.name}</strong><small>{product.sku||product.barcode||t.noSkuBarcode}</small></span><b className={low?'stock-low':''}>{Number(product.stock)} {product.unit}</b></button>})}</div></section>
    <aside className="card stock-adjust-card"><span className="page-kicker">{t.ownerControl}</span><h2>{t.adjustStock}</h2>{selected?<><div className="selected-stock"><span>{selected.name}</span><strong>{Number(selected.stock)} {selected.unit}</strong></div><form onSubmit={adjust}><div className="segmented"><button type="button" className={mode==='IN'?'active':''} onClick={()=>setMode('IN')}>{t.stockIn}</button><button type="button" className={mode==='OUT'?'active':''} onClick={()=>setMode('OUT')}>{t.stockOut}</button></div><div className="field"><label>{t.quantity} *</label><input className="input" required type="number" min="0.001" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></div><div className="field"><label>{t.reasonNote}</label><input className="input" placeholder={t.reasonPlaceholder} value={note} onChange={e=>setNote(e.target.value)}/></div><button className="btn btn-primary full-button" disabled={saving}>{saving?t.updating:mode==='IN'?t.addStock:t.removeStock}</button></form></>:<div className="empty-state">{t.selectProductAdjust}</div>}</aside></div>
    <section className="card pos-panel inventory-history"><div className="section-head"><div><span className="page-kicker">{t.movementHistory}</span><h2>{t.latestStockActivity}</h2></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>{t.product}</th><th>{t.type}</th><th>{t.change}</th><th>{t.stockAfter}</th><th>{t.note}</th><th>{t.time}</th></tr></thead><tbody>{movements.length===0?<tr><td colSpan={6}><div className="empty-state">{t.noMovements}</div></td></tr>:movements.map(m=><tr key={m.id}><td><strong>{m.products?.name||t.product}</strong></td><td>{m.movement_type.replaceAll('_',' ')}</td><td><strong className={Number(m.quantity_change)<0?'text-danger':''}>{Number(m.quantity_change)>0?'+':''}{Number(m.quantity_change)}</strong></td><td>{Number(m.stock_after)}</td><td>{m.note||'—'}</td><td>{formatDateTime(m.created_at)}</td></tr>)}</tbody></table></div></section>
  </OwnerShell>;
}
