org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
BRANDSPIRE_SUPABASE_URL=https://elrohkyuvebgjgfppcsj.supabase.co
BRANDSPIRE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscm9oa3l1dmViZ2pnZnBwY3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3NTQ4NjAsImV4cCI6MjEwMzMzMDg2MH0.CPTmJTS_ot7Yj8gPJMkBpe1XDzvByV27YRP8rclSOnQ

# Android emulator -> Windows host localhost
BRANDSPIRE_API_BASE_URL=http://10.0.2.2:3001