'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import OwnerShell from '@/components/pos/OwnerShell';
import WorkspaceLoader from '@/components/pos/WorkspaceLoader';
import { getCurrentOrganization, type CurrentOrganization } from '@/lib/pos';
import { posText } from '@/lib/pos-i18n';
import { createStaff, listStaff, resetStaffPassword, setStaffStatus, type StaffRecord } from '@/lib/owner-api';

export default function OwnerStaffPage(){
  const router=useRouter();const[org,setOrg]=useState<CurrentOrganization|null>(null);const[staff,setStaff]=useState<StaffRecord[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');const[form,setForm]=useState({fullName:'',email:'',phone:'',temporaryPassword:''});
  async function refresh(){const result=await listStaff();setStaff(result.data);}
  useEffect(()=>{async function load(){try{const current=await getCurrentOrganization();if(!current)return router.replace('/auth/login');if(current.role!=='OWNER')return router.replace('/staff');setOrg(current);await refresh();}catch(err){setError(err instanceof Error?err.message:'Could not load Staff.');}finally{setLoading(false);}}load();},[router]);
  const t=posText(org?.preferredLanguage??'en');
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');setSuccess('');try{await createStaff(form);setSuccess(`${t.staffCreatedSuccess} ${form.fullName}`);setForm({fullName:'',email:'',phone:'',temporaryPassword:''});await refresh();}catch(err){setError(err instanceof Error?err.message:'Could not create Staff account.');}finally{setSaving(false);}}
  async function toggle(member:StaffRecord){setError('');setSuccess('');try{await setStaffStatus(member.userId,!member.active);await refresh();}catch(err){setError(err instanceof Error?err.message:'Could not update Staff access.');}}
  async function reset(member:StaffRecord){const prompt=org?.preferredLanguage==='hi'?`${member.fullName} के लिए नया temporary password डालें। कम से कम 8 अक्षर।`:org?.preferredLanguage==='hinglish'?`${member.fullName} ke liye naya temporary password set karo. Minimum 8 characters.`:`Set a new temporary password for ${member.fullName}. Minimum 8 characters.`;const password=window.prompt(prompt);if(!password)return;setError('');setSuccess('');try{await resetStaffPassword(member.userId,password);setSuccess(org?.preferredLanguage==='hi'?`${member.fullName} का temporary password अपडेट हो गया।`:org?.preferredLanguage==='hinglish'?`${member.fullName} ka temporary password update ho gaya.`:`Temporary password updated for ${member.fullName}.`);}catch(err){setError(err instanceof Error?err.message:'Could not reset password.');}}
  if(loading||!org)return <WorkspaceLoader/>;
  return <OwnerShell businessName={org.organizationName} language={org.preferredLanguage}>
    <div className="content-head pos-page-head"><div><span className="page-kicker">{t.staffKicker}</span><h1>{t.staffTitle}</h1><p>{t.staffSub}</p></div><div className="staff-count-pill"><strong>{staff.filter(item=>item.active).length}</strong><span>{t.activeStaff}</span></div></div>
    {error&&<div className="form-error">{error}</div>}{success&&<div className="form-success">{success}</div>}
    <div className="settings-layout">
      <section className="card settings-card staff-create-card"><div className="settings-section-head"><span className="section-icon">+</span><div><h2>{t.addStaff}</h2><p>{t.addStaffSub}</p></div></div><form onSubmit={submit} className="settings-form"><div className="field"><label>{t.staffName}</label><input className="input" required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="e.g. Rahul Kumar"/></div><div className="field"><label>{t.email}</label><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="rahul@shop.com"/></div><div className="field"><label>{t.mobileNumber}</label><input className="input" inputMode="numeric" maxLength={10} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value.replace(/\D/g,'')})} placeholder="10-digit mobile"/></div><div className="field"><label>{t.temporaryPassword}</label><input className="input" type="password" minLength={8} required value={form.temporaryPassword} onChange={e=>setForm({...form,temporaryPassword:e.target.value})} placeholder={t.minimum8}/></div><button className="btn btn-primary settings-save" disabled={saving}>{saving?t.creatingAccount:t.createStaffAccount}</button></form><div className="permission-strip"><strong>{t.staffPermissionBoundary}</strong><span>✓ {t.addCustomer}</span><span>✓ {t.addProduct}</span><span>✓ {t.createBill}</span><span className="denied">× {t.noDeleteSettingsSubscription}</span></div></section>
      <section className="card settings-card"><div className="settings-section-head"><span className="section-icon neutral">ST</span><div><h2>{t.yourStaff}</h2><p>{t.yourStaffSub}</p></div></div><div className="staff-list">{staff.length===0?<div className="empty-state">{t.noStaffAccounts}</div>:staff.map(member=><article className="staff-row" key={member.userId}><div className="staff-avatar">{member.fullName.split(' ').slice(0,2).map(part=>part[0]?.toUpperCase()).join('')}</div><div className="staff-main"><strong>{member.fullName}</strong><span>{member.email}</span><small>{member.phone||t.noPhoneAdded}</small></div><span className={`access-chip ${member.active?'on':'off'}`}>{member.active?t.active:t.inactive}</span><div className="staff-actions"><button className="btn btn-small" onClick={()=>reset(member)}>{t.resetPassword}</button><button className={`btn btn-small ${member.active?'btn-soft-danger':''}`} onClick={()=>toggle(member)}>{member.active?t.deactivate:t.activate}</button></div></article>)}</div></section>
    </div>
  </OwnerShell>;
}
