import type { PosLanguage } from '@/lib/pos-i18n';

const text = {
  en: {
    nav:'Subscription', kicker:'Subscription & Access', title:'Keep Brandspire POS active.', sub:'View your plan, billing status and Cashfree subscription in one place.', current:'Current access', activeUntil:'Active until', planOptions:'Choose a plan', monthly:'Monthly', yearly:'Yearly', saveYearly:'Best value', start:'Start subscription', notConfigured:'Online subscription payments are not configured yet. Brandspire Admin can still manage your access manually.', paymentHistory:'Payment history', noPayments:'No subscription payments recorded yet.', providerStatus:'Provider status', nextCharge:'Next charge', cancel:'Cancel renewal', cancelConfirm:'Your current paid period will remain available. Cancel automatic renewal at the end of the billing cycle?', finalizing:'Payment verified. Finalizing your subscription…', activated:'Subscription verified successfully.', checkoutFailed:'Checkout could not be completed.', configureAdmin:'Admin must sync this plan with Cashfree first.'
  },
  hinglish: {
    nav:'Subscription', kicker:'Subscription & Access', title:'Brandspire POS ko active rakho.', sub:'Apna plan, billing status aur Cashfree subscription ek hi jagah dekho.', current:'Current Access', activeUntil:'Active till', planOptions:'Plan Choose Karo', monthly:'Monthly', yearly:'Yearly', saveYearly:'Best Value', start:'Subscription Start Karo', notConfigured:'Online subscription payment abhi configure nahi hai. Brandspire Admin manual access de sakta hai.', paymentHistory:'Payment History', noPayments:'Abhi koi subscription payment record nahi hai.', providerStatus:'Provider Status', nextCharge:'Next Charge', cancel:'Renewal Cancel Karo', cancelConfirm:'Current paid period chalta rahega. Billing cycle ke end par auto-renewal cancel karna hai?', finalizing:'Payment verify ho gaya. Subscription activate ho rahi hai…', activated:'Subscription successfully verify ho gayi.', checkoutFailed:'Checkout complete nahi ho paya.', configureAdmin:'Brandspire Admin ko pehle is plan ko Cashfree se sync karna hoga.'
  },
  hi: {
    nav:'सदस्यता', kicker:'सदस्यता और पहुँच', title:'Brandspire POS को सक्रिय रखें।', sub:'अपनी योजना, बिलिंग स्थिति और Cashfree सदस्यता एक ही स्थान पर देखें।', current:'वर्तमान पहुँच', activeUntil:'सक्रिय अवधि', planOptions:'योजना चुनें', monthly:'मासिक', yearly:'वार्षिक', saveYearly:'बेहतर मूल्य', start:'सदस्यता शुरू करें', notConfigured:'ऑनलाइन सदस्यता भुगतान अभी कॉन्फ़िगर नहीं है। Brandspire Admin मैन्युअल पहुँच दे सकता है।', paymentHistory:'भुगतान इतिहास', noPayments:'अभी कोई सदस्यता भुगतान दर्ज नहीं है।', providerStatus:'प्रदाता स्थिति', nextCharge:'अगला भुगतान', cancel:'नवीनीकरण रद्द करें', cancelConfirm:'वर्तमान भुगतान अवधि जारी रहेगी। क्या बिलिंग चक्र के अंत में स्वतः नवीनीकरण रद्द करना है?', finalizing:'भुगतान सत्यापित हो गया। सदस्यता सक्रिय की जा रही है…', activated:'सदस्यता सफलतापूर्वक सत्यापित हो गई।', checkoutFailed:'चेकआउट पूरा नहीं हो सका।', configureAdmin:'Brandspire Admin को पहले इस योजना को Cashfree से सिंक करना होगा।'
  }
} as const;

export function phase9Text(language: PosLanguage) { return text[language] ?? text.en; }
