import type { PosLanguage } from '@/lib/pos-i18n';

const copy = {
  en: {
    ledger: 'Customer Ledger', returns: 'Returns & Refunds',
    ledgerKicker: 'CUSTOMER LEDGER', ledgerTitle: 'Every rupee, in one timeline.', ledgerSub: 'See invoices, payments, refunds and credit notes for a customer without changing the original records.',
    selectCustomer: 'Select customer', chooseCustomer: 'Choose a customer to view the ledger.', currentOutstanding: 'Current outstanding', ledgerHistory: 'Ledger history', debit: 'Debit', credit: 'Credit', balance: 'Balance', reference: 'Reference', details: 'Details', noLedger: 'No ledger entries yet.', loadingLedger: 'Loading ledger…',
    returnsKicker: 'RETURNS & REFUNDS', returnsTitle: 'Return safely. Keep the original bill.', returnsSub: 'Owner-only credit notes restore returned stock and record the refund without deleting or rewriting the invoice.', selectPaidInvoice: 'Select a paid invoice', chooseInvoice: 'Choose a fully-paid invoice that needs a return or refund.', returnItems: 'Return items', returnQty: 'Return Qty', remainingReturnable: 'Returnable', refundMethod: 'Refund Method', reason: 'Reason', reasonHint: 'Damaged item, customer return, wrong product…', issueCreditNote: 'Issue Credit Note & Refund', issuing: 'Issuing…', creditNoteIssued: 'Credit note issued successfully.', noEligibleInvoices: 'No fully-paid invoices are currently eligible for a refund.', originalQty: 'Sold Qty', alreadyReturned: 'Already Returned', refundEstimate: 'Estimated refund', ownerOnly: 'Owner only', auditSafe: 'Stock restoration and audit log are automatic.', walkIn: 'Walk-in Customer', paid: 'Paid', credited: 'credited', selectReturnItem: 'Select at least one return item and quantity.',
    offlineMode: 'Offline Help', ownerAssistHead: 'Offline help + Owner insights', controlledToolsFoot: 'Controlled business tools · No arbitrary SQL', offlineFoot: 'Offline knowledge · No business data sent', onlineInsights: 'Online Business Insights', onlineInsightsSub: 'Ask Brandspire Assist about sales, top products, low stock or pending payments. Your database is never exposed directly to the AI provider.', askBusiness: 'Ask about your business…', aiUnavailable: 'Online AI is not configured yet. Offline Brandspire Assist continues to work.',
  },
  hinglish: {
    ledger: 'Customer Ledger', returns: 'Returns & Refunds',
    ledgerKicker: 'CUSTOMER LEDGER', ledgerTitle: 'Har rupee ka clear timeline.', ledgerSub: 'Customer ke invoices, payments, refunds aur credit notes ek jagah dekho. Original records safe rahenge.',
    selectCustomer: 'Customer Select Karo', chooseCustomer: 'Ledger dekhne ke liye customer choose karo.', currentOutstanding: 'Current Baaki Amount', ledgerHistory: 'Ledger History', debit: 'Debit', credit: 'Credit', balance: 'Balance', reference: 'Reference', details: 'Details', noLedger: 'Abhi koi ledger entry nahi hai.', loadingLedger: 'Ledger load ho raha hai…',
    returnsKicker: 'RETURNS & REFUNDS', returnsTitle: 'Return safe rakho. Original bill ko mat badlo.', returnsSub: 'Owner-only credit note returned stock restore karta hai aur refund record karta hai bina invoice delete ya rewrite kiye.', selectPaidInvoice: 'Paid Invoice Select Karo', chooseInvoice: 'Return/refund ke liye fully-paid invoice choose karo.', returnItems: 'Return Items', returnQty: 'Return Qty', remainingReturnable: 'Returnable', refundMethod: 'Refund Method', reason: 'Reason', reasonHint: 'Damaged item, customer return, wrong product…', issueCreditNote: 'Credit Note & Refund Issue Karo', issuing: 'Issue ho raha hai…', creditNoteIssued: 'Credit note successfully issue ho gaya.', noEligibleInvoices: 'Abhi refund ke liye koi fully-paid invoice eligible nahi hai.', originalQty: 'Sold Qty', alreadyReturned: 'Already Returned', refundEstimate: 'Estimated Refund', ownerOnly: 'Owner only', auditSafe: 'Stock restore aur audit log automatically hoga.', walkIn: 'Walk-in Customer', paid: 'Paid', credited: 'credited', selectReturnItem: 'Kam se kam ek return item aur quantity select karo.',
    offlineMode: 'Offline Help', ownerAssistHead: 'Offline help + Owner insights', controlledToolsFoot: 'Controlled business tools · Arbitrary SQL nahi', offlineFoot: 'Offline knowledge · Koi business data send nahi hota', onlineInsights: 'Online Business Insights', onlineInsightsSub: 'Brandspire Assist se sales, top products, low stock ya pending payments ke baare mein pucho. AI provider ko direct database access nahi milta.', askBusiness: 'Apne business ke baare mein pucho…', aiUnavailable: 'Online AI abhi configure nahi hai. Offline Brandspire Assist normal kaam karta rahega.',
  },
  hi: {
    ledger: 'ग्राहक लेजर', returns: 'रिटर्न और रिफंड',
    ledgerKicker: 'ग्राहक लेजर', ledgerTitle: 'हर रुपये का साफ़ हिसाब।', ledgerSub: 'ग्राहक के बिल, भुगतान, रिफंड और क्रेडिट नोट एक ही टाइमलाइन में देखें। मूल रिकॉर्ड सुरक्षित रहेंगे।',
    selectCustomer: 'ग्राहक चुनें', chooseCustomer: 'लेजर देखने के लिए ग्राहक चुनें।', currentOutstanding: 'वर्तमान बकाया राशि', ledgerHistory: 'लेजर इतिहास', debit: 'डेबिट', credit: 'क्रेडिट', balance: 'शेष', reference: 'संदर्भ', details: 'विवरण', noLedger: 'अभी कोई लेजर प्रविष्टि नहीं है।', loadingLedger: 'लेजर लोड हो रहा है…',
    returnsKicker: 'रिटर्न और रिफंड', returnsTitle: 'रिटर्न सुरक्षित रखें। मूल बिल न बदलें।', returnsSub: 'केवल Owner क्रेडिट नोट जारी कर सकता है। लौटाया गया स्टॉक वापस जुड़ता है और रिफंड रिकॉर्ड होता है, बिना बिल हटाए।', selectPaidInvoice: 'भुगतान किए गए बिल चुनें', chooseInvoice: 'रिटर्न या रिफंड के लिए पूरा भुगतान किया गया बिल चुनें।', returnItems: 'लौटाई जाने वाली वस्तुएँ', returnQty: 'रिटर्न मात्रा', remainingReturnable: 'वापसी योग्य', refundMethod: 'रिफंड का तरीका', reason: 'कारण', reasonHint: 'खराब सामान, ग्राहक रिटर्न, गलत उत्पाद…', issueCreditNote: 'क्रेडिट नोट और रिफंड जारी करें', issuing: 'जारी किया जा रहा है…', creditNoteIssued: 'क्रेडिट नोट सफलतापूर्वक जारी हो गया।', noEligibleInvoices: 'अभी रिफंड के लिए कोई पूर्ण-भुगतान बिल उपलब्ध नहीं है।', originalQty: 'बेची मात्रा', alreadyReturned: 'पहले लौटाया', refundEstimate: 'अनुमानित रिफंड', ownerOnly: 'केवल Owner', auditSafe: 'स्टॉक वापसी और ऑडिट लॉग अपने-आप होगा।', walkIn: 'वॉक-इन ग्राहक', paid: 'भुगतान पूरा', credited: 'क्रेडिट', selectReturnItem: 'कम से कम एक रिटर्न वस्तु और मात्रा चुनें।',
    offlineMode: 'ऑफलाइन सहायता', ownerAssistHead: 'ऑफलाइन सहायता + Owner इनसाइट्स', controlledToolsFoot: 'नियंत्रित बिज़नेस टूल्स · मनमाना SQL नहीं', offlineFoot: 'ऑफलाइन जानकारी · कोई बिज़नेस डेटा नहीं भेजा जाता', onlineInsights: 'ऑनलाइन बिज़नेस इनसाइट्स', onlineInsightsSub: 'Brandspire Assist से बिक्री, शीर्ष उत्पाद, कम स्टॉक या लंबित भुगतान के बारे में पूछें। AI प्रदाता को डेटाबेस का सीधा एक्सेस नहीं मिलता।', askBusiness: 'अपने व्यवसाय के बारे में पूछें…', aiUnavailable: 'ऑनलाइन AI अभी कॉन्फ़िगर नहीं है। ऑफलाइन Brandspire Assist काम करता रहेगा।',
  }
} as const;

export function phase8Text(language: PosLanguage) { return copy[language] ?? copy.en; }
