export type PosLanguage = 'en' | 'hi' | 'hinglish';

const en = {
  dashboard: 'Dashboard', createBill: 'Create Bill', customers: 'Customers', products: 'Products', inventory: 'Inventory', invoices: 'Bills', dues: 'Dues & Payments', reports: 'Reports', staff: 'Staff', settings: 'Settings', logout: 'Logout',
  ownerWorkspace: 'Owner workspace', staffWorkspace: 'Staff workspace', secureWorkspace: 'Secure workspace', softwareSolutions: 'Software solutions for growing businesses',
  todaySales: "Today's Sales", todayBills: "Today's Bills", lowStock: 'Low Stock', outstanding: 'Outstanding', recentBills: 'Recent Bills',
  addCustomer: 'Add Customer', addProduct: 'Add Product', quickActions: 'Quick Actions', subscription: 'Subscription',
  dashboardGreeting: 'Good to see you.', dashboardSub: 'Everything important for your business, without the clutter.',
  runCounter: 'Run the counter faster', latestActivity: 'Latest activity', viewAll: 'View all',
  salesHint: 'Live from completed bills', billsHint: 'Bills created today', duesHint: 'Customer dues', stockHint: 'Products needing attention',
  loadingBrandspire: 'Loading Brandspire POS', preparingWorkspace: 'Preparing your workspace', checkingAccount: 'Checking account', loadingBusiness: 'Loading business', syncingSettings: 'Syncing settings', almostReady: 'Almost ready',
  assist: 'Brandspire Assist', offlineHelp: 'Offline help', assistIntro: 'Ask how to use Brandspire POS. This help works without internet.', assistPlaceholder: 'Ask about billing, printer, customers…', assistNoMatch: 'I could not match that exactly. Try asking about billing, printer, customers, products, payments, Staff or settings.', close: 'Close', clear: 'Clear',
  helpBillQ: 'How do I create a bill?', helpPrinterQ: 'How do I print a bill?', helpDueQ: 'How do I receive a pending payment?', helpCustomerQ: 'How do I add a customer?',
  customersKicker: 'CUSTOMERS', customersTitle: 'People you sell to.', customersSub: 'Keep customer details and outstanding amounts in one clean place.', newCustomer: 'New customer', newCustomerSub: 'Only name is required. Add the rest when useful.', name: 'Name', phone: 'Phone', email: 'Email', gstin: 'GSTIN', state: 'State', address: 'Address', cancel: 'Cancel', saveCustomer: 'Save Customer', saving: 'Saving…', searchCustomer: 'Search name, phone, email or GSTIN…', customer: 'Customer', contact: 'Contact', noCustomers: 'No customers found.', noAddress: 'No address added', remove: 'Remove', removeCustomerConfirm: 'Remove this customer? Their history will stay safe.',
  productsKicker: 'PRODUCTS', productsTitle: 'Your sellable catalog.', productsSub: 'Prices, GST and stock designed for a fast counter workflow.', newProduct: 'New product', newProductSub: 'Add the essentials now. You can expand the catalog later.', productName: 'Product Name', sellingPrice: 'Selling Price ₹', sku: 'SKU', barcode: 'Barcode', purchasePrice: 'Purchase Price ₹', openingStock: 'Opening Stock', gstRate: 'GST Rate', hsnSac: 'HSN / SAC', unit: 'Unit', lowStockAlert: 'Low Stock Alert At', priceIncludesGst: 'Selling price already includes GST', saveProduct: 'Save Product', searchProduct: 'Search product, SKU, barcode or HSN…', product: 'Product', price: 'Price', gst: 'GST', stock: 'Stock', noProducts: 'No products found.', noSku: 'No SKU', gstIncluded: 'GST included', gstExtra: 'GST extra', inStock: 'In stock', removeProductConfirm: 'Remove this product? Old bills will keep their product snapshot.',
  inventoryKicker: 'INVENTORY', inventoryTitle: 'Stock you can trust.', inventorySub: 'Owner-only stock in/out with permanent movement history. Sales continue to reduce stock automatically.', ownerControl: 'OWNER CONTROL', adjustStock: 'Adjust stock', stockIn: 'Stock In', stockOut: 'Stock Out', quantity: 'Quantity', reasonNote: 'Reason / Note', reasonPlaceholder: 'Purchase received, damaged item…', addStock: 'Add Stock', removeStock: 'Remove Stock', updating: 'Updating…', selectProductAdjust: 'Select a product to adjust stock.', movementHistory: 'MOVEMENT HISTORY', latestStockActivity: 'Latest stock activity', type: 'Type', change: 'Change', stockAfter: 'Stock After', note: 'Note', time: 'Time', noMovements: 'No stock movements yet.', searchProductSkuBarcode: 'Search product, SKU or barcode…', noSkuBarcode: 'No SKU / barcode',
  invoicesKicker: 'BILLS', invoicesTitle: 'Invoice history.', invoicesSub: 'Open any bill to review details or print in 58mm, 80mm or A4 format.', payment: 'Payment', total: 'Total', due: 'Due', noBills: 'No bills yet.', walkInCustomer: 'Walk-in Customer', viewPrint: 'View / Print',
  duesKicker: 'DUES & PAYMENTS', duesTitle: 'Collect what is pending.', duesSub: 'Record later and partial payments without changing the original bill.', totalOutstanding: 'Total Outstanding', acrossOpenInvoices: 'Across open invoices', openBills: 'Open Bills', invoicesPending: 'Invoices with pending amount', customersWithDues: 'Customers with current dues', collection: 'Collection', ownerOnly: 'Owner only', protectedByDatabase: 'Protected by database authorization', openDues: 'OPEN DUES', pendingInvoices: 'Pending invoices', refresh: 'Refresh', refreshing: 'Refreshing…', loadingOutstanding: 'Loading outstanding bills…', nothingDue: 'Nothing is due.', allPaid: 'All currently eligible invoices are fully paid.', receivePayment: 'RECEIVE PAYMENT', recordPayment: 'Record payment', selectInvoice: 'Select an invoice', choosePendingInvoice: 'Choose a pending invoice from the left to record cash, UPI, card or another payment.', dueNow: 'Due now', amount: 'Amount', paymentMethod: 'Payment Method', optional: 'optional', notePlaceholder: 'Reference, collection note, etc.', recording: 'Recording…', openInvoice: 'Open Invoice', enterValidPayment: 'Enter a valid payment amount.', paymentRecorded: 'Payment recorded.', stillDue: 'is still due.', invoiceFullyPaid: 'Invoice is fully paid.',
  reportsKicker: 'REPORTS', reportsTitle: 'Know what is moving your business.', reportsSub: 'Sales, collections, GST, products, staff activity and stock signals in one clean view.', days: 'days', sales: 'Sales', collected: 'Collected', moneyReceived: 'Money received', dueInRange: 'From bills in this range', averageBill: 'Average Bill', averageInvoiceValue: 'Average invoice value', gstSummary: 'GST SUMMARY', taxView: 'Tax view for this period', cancelledExcluded: 'Cancelled and refunded invoices are excluded.', totalGst: 'Total GST', taxableSales: 'Taxable Sales', totalTax: 'Total Tax', salesTrend: 'SALES TREND', dailySales: 'Daily sales', noSalesPeriod: 'No sales in this period.', payments: 'PAYMENTS', paymentMix: 'Payment mix', noPaymentData: 'No payment data.', topSellers: 'Top sellers', noProductSales: 'No product sales yet.', sold: 'sold', staffCreatedBills: 'Staff-created bills', noStaffBills: 'No staff-created bills in this period.', needsAttention: 'Needs attention', stockHealthy: 'Stock levels look healthy.', alertAt: 'Alert at',
  settingsKicker: 'BUSINESS SETTINGS', settingsTitle: 'Set it once. Bill faster.', settingsSub: 'Business identity, language, invoice behaviour and default printer — in one clean place.', businessProfile: 'Business profile', businessProfileSub: 'This information appears on invoices and receipts.', businessName: 'Business Name', city: 'City', pincode: 'Pincode', languageBilling: 'Language & billing', languageBillingSub: 'Choose the natural working language and counter defaults.', language: 'Language', invoicePrefix: 'Invoice Prefix', defaultPayment: 'Default Payment', printerReceipt: 'Printer & receipt', printerReceiptSub: 'Brandspire POS supports 2-inch, 3-inch and A4 layouts.', thermalReceipt58: '58mm thermal receipt', thermalReceipt80: '80mm thermal receipt', fullPageGstInvoice: 'Full-page GST invoice', printCopies: 'Print Copies', showGstinReceipt: 'Show GSTIN on receipt', recommendedGst: 'Recommended for GST businesses', allowNegativeStock: 'Allow negative stock', saferInventory: 'Keep off for safer inventory', receiptHeader: 'Receipt Header', receiptFooter: 'Receipt Footer', staffBillingPolicy: 'Staff billing policy', staffBillingPolicySub: 'Staff remains restricted. You may optionally allow a limited percentage discount.', allowStaffDiscount: 'Allow Staff discount', backendPolicy: 'Backend enforcement uses this policy in the billing engine.', maximumPercent: 'Maximum %', readySave: 'Ready to save?', changesBusinessOnly: 'Changes apply to this business only.', saveSettings: 'Save Settings', settingsSaved: 'Settings saved. Language changes apply across the workspace.',
  staffKicker: 'TEAM ACCESS', staffTitle: 'Staff, kept simple.', staffSub: 'Create individual counter accounts and control access without sharing the Owner login.', activeStaff: 'active staff', addStaff: 'Add Staff', addStaffSub: 'Staff can only add customers, add products and create bills.', staffName: 'Staff Name', mobileNumber: 'Mobile Number', temporaryPassword: 'Temporary Password', minimum8: 'Minimum 8 characters', createStaffAccount: 'Create Staff Account', creatingAccount: 'Creating account…', staffPermissionBoundary: 'Staff permission boundary', noDeleteSettingsSubscription: 'No delete / settings / subscription', yourStaff: 'Your Staff', yourStaffSub: 'Deactivate access instantly without deleting business history.', noStaffAccounts: 'No Staff accounts yet.', noPhoneAdded: 'No phone added', active: 'Active', inactive: 'Inactive', resetPassword: 'Reset password', deactivate: 'Deactivate', activate: 'Activate', staffCreatedSuccess: 'Staff account created. Share the temporary password securely.',
  counterKickerOwner: 'FAST BILLING', counterKickerStaff: 'STAFF COUNTER', counterOwnerTitle: 'Create a bill.', counterStaffTitle: 'Create a new bill.', counterSub: 'Search products, take payment and finish. The invoice is saved before printing.', searchFocused: 'Search stays focused', billCreated: 'BILL CREATED', stockUpdated: 'stock updated automatically', newBill: 'New Bill', scanSearch: 'Scan barcode / SKU or search product…', noMatchingProducts: 'No matching products.', currentBill: 'CURRENT BILL', item: 'item', items: 'items', startProduct: 'Start with a product.', searchTapAdd: 'Search on the left and tap to add.', discount: 'Discount', percentage: 'Percentage %', flat: 'Flat ₹', value: 'Value', ownerDiscountLimit: 'Owner limit', discountOwnerOnly: 'Discount is Owner-only for this business.', amountPaid: 'Amount Paid', amountPaidHint: 'blank = full payment; Credit = ₹0', taxable: 'Taxable', creatingBill: 'Creating Bill…', transactionSavedFirst: 'Transaction saved first. Printing can fail without losing the bill.',
  staffCustomersKicker:'CUSTOMERS · STAFF', staffCustomersTitle:'Add a customer.', staffCustomersSub:'Only the details needed at the counter. Management and deletion stay with the Owner.', staffCustomerNewSub:'Name is enough to start.', staffProductsKicker:'PRODUCTS · STAFF', staffProductsTitle:'Add a sellable product.', staffProductsSub:'Staff can create products for billing. Editing, deleting and sensitive management stay Owner-only.', staffProductNewSub:'Keep it quick: name, selling price, GST and stock.', noStateAdded:'No state added', noCode:'No code',
  staffFastCounter: 'FAST COUNTER', staffReadyTitle: 'Ready for the next customer.', staffPausedTitle: 'Business access is paused.', staffReadySub: 'Everything Staff needs is one tap away. Create the bill first; customer and product setup stay simple.', staffPausedSub: 'The Owner subscription is not active. Ask the Owner to contact the Brandspire Team.', staffCustomerHelp: 'Quick customer entry. Staff can add and search, never delete.', staffProductHelp: 'Add a sellable item with GST, price and opening stock.', staffRule: 'Staff = operate. Owner = manage. Destructive and subscription actions remain Owner-only.',
  noBillsDashboard: 'No bills yet. Your first bill will appear here.', searchTakeFinish: 'Search products, take payment, finish.', saveCustomerDues: 'Save customer details and dues.', addStockGstPrice: 'Add stock, GST and selling price.',
  date:'Date', invoiceKicker:'INVOICE', back:'Back', downloadPdf:'Download PDF', sharePdf:'Share PDF', collectPayment:'Collect Payment', cancelledInvoice:'Cancelled invoice', noReasonRecorded:'No reason recorded', noPaymentMethod:'No payment method', created:'Created', status:'Status', from:'FROM', billTo:'BILL TO', businessAddressMissing:'Business address not added', noAddressShort:'No address', qty:'Qty', rate:'Rate', subtotal:'Subtotal', grandTotal:'Grand Total', paid:'Paid', paymentHistory:'PAYMENT HISTORY', moneyReceivedHistory:'Money received', noPaymentRecorded:'No payment has been recorded against this invoice.', cancelInvoiceTitle:'Cancel this invoice', cancelSafeCopy:'Cancellation restores sold stock and removes any unpaid customer due.', cancelPaidCopy:'This invoice already has a captured payment. Use the refund/credit-note flow instead of cancelling it.', cancelInvoice:'Cancel Invoice', cancelReasonPlaceholder:'Reason for cancellation (required)', keepInvoice:'Keep Invoice', confirmCancellation:'Confirm Cancellation', cancelling:'Cancelling…', printFormat:'PRINT FORMAT', printTitle:'Print exactly how you need it.', printSub:'Choose 58mm, 80mm or A4. Desktop uses the installed printer driver; Android direct Bluetooth/USB printing uses the native printer bridge.', thermal2:'2-inch thermal', thermal3:'3-inch thermal', a4Invoice:'A4 invoice', print:'Print', pdfSharing:'PDF sharing', shareNote:'On supported phones/tablets, Share PDF opens the native share sheet for WhatsApp or other apps.',
  subscriptionTrialFallback: 'Enjoy your Brandspire POS free session. Explore faster billing and simpler business management.', subscriptionActiveFallback: 'Your Brandspire POS access is active. Keep billing without interruption.', subscriptionBlockedFallback: 'Your Brandspire POS access is restricted. Contact the Brandspire Team for assistance.', trialValidUntil: 'Trial valid until', accessValidUntil: 'Access valid until', free: 'FREE', live: 'LIVE'
};

type Messages = { [K in keyof typeof en]: string };

const hi: Messages = {
  ...en,
  dashboard:'डैशबोर्ड',createBill:'बिल बनाएं',customers:'ग्राहक',products:'प्रोडक्ट',inventory:'इन्वेंटरी',invoices:'बिल',dues:'बकाया और भुगतान',reports:'रिपोर्ट्स',staff:'स्टाफ',settings:'सेटिंग्स',logout:'लॉग आउट',
  ownerWorkspace:'ओनर वर्कस्पेस',staffWorkspace:'स्टाफ वर्कस्पेस',secureWorkspace:'सुरक्षित वर्कस्पेस',softwareSolutions:'बढ़ते व्यवसायों के लिए सॉफ्टवेयर समाधान',
  todaySales:'आज की बिक्री',todayBills:'आज के बिल',lowStock:'कम स्टॉक',outstanding:'बकाया',recentBills:'हाल के बिल',addCustomer:'ग्राहक जोड़ें',addProduct:'प्रोडक्ट जोड़ें',quickActions:'त्वरित कार्य',subscription:'सब्सक्रिप्शन',dashboardGreeting:'आपका स्वागत है।',dashboardSub:'आपके व्यवसाय की जरूरी जानकारी, बिना किसी उलझन के।',runCounter:'काउंटर को और तेज चलाएं',latestActivity:'हाल की गतिविधि',viewAll:'सभी देखें',salesHint:'पूरे हुए बिलों से लाइव',billsHint:'आज बनाए गए बिल',duesHint:'ग्राहकों का बकाया',stockHint:'ध्यान देने वाले प्रोडक्ट',
  loadingBrandspire:'Brandspire POS लोड हो रहा है',preparingWorkspace:'आपका वर्कस्पेस तैयार हो रहा है',checkingAccount:'अकाउंट जांच रहे हैं',loadingBusiness:'बिज़नेस लोड हो रहा है',syncingSettings:'सेटिंग्स सिंक हो रही हैं',almostReady:'बस तैयार है',
  assist:'Brandspire Assist',offlineHelp:'ऑफलाइन सहायता',assistIntro:'Brandspire POS इस्तेमाल करने के बारे में पूछें। यह सहायता बिना इंटरनेट भी काम करती है।',assistPlaceholder:'बिलिंग, प्रिंटर, ग्राहक आदि के बारे में पूछें…',assistNoMatch:'यह सवाल ठीक से नहीं मिला। बिलिंग, प्रिंटर, ग्राहक, प्रोडक्ट, भुगतान, स्टाफ या सेटिंग्स के बारे में पूछें।',close:'बंद करें',clear:'साफ करें',
  helpBillQ:'बिल कैसे बनाएं?',helpPrinterQ:'बिल कैसे प्रिंट करें?',helpDueQ:'बकाया भुगतान कैसे लें?',helpCustomerQ:'ग्राहक कैसे जोड़ें?',
  customersKicker:'ग्राहक',customersTitle:'जिन लोगों को आप बेचते हैं।',customersSub:'ग्राहक की जानकारी और बकाया राशि एक साफ जगह पर रखें।',newCustomer:'नया ग्राहक',newCustomerSub:'केवल नाम जरूरी है। बाकी जानकारी जरूरत के अनुसार जोड़ें।',name:'नाम',phone:'फोन',email:'ईमेल',state:'राज्य',address:'पता',cancel:'रद्द करें',saveCustomer:'ग्राहक सेव करें',saving:'सेव हो रहा है…',searchCustomer:'नाम, फोन, ईमेल या GSTIN खोजें…',customer:'ग्राहक',contact:'संपर्क',noCustomers:'कोई ग्राहक नहीं मिला।',noAddress:'पता नहीं जोड़ा गया',remove:'हटाएं',removeCustomerConfirm:'क्या इस ग्राहक को हटाना है? पुराना इतिहास सुरक्षित रहेगा।',
  productsKicker:'प्रोडक्ट',productsTitle:'आपका बिक्री कैटलॉग।',productsSub:'तेज काउंटर के लिए कीमत, GST और स्टॉक एक जगह।',newProduct:'नया प्रोडक्ट',newProductSub:'जरूरी जानकारी अभी जोड़ें। बाद में कैटलॉग बढ़ा सकते हैं।',productName:'प्रोडक्ट नाम',sellingPrice:'बिक्री मूल्य ₹',purchasePrice:'खरीद मूल्य ₹',openingStock:'शुरुआती स्टॉक',gstRate:'GST दर',unit:'इकाई',lowStockAlert:'कम स्टॉक अलर्ट',priceIncludesGst:'बिक्री मूल्य में GST पहले से शामिल है',saveProduct:'प्रोडक्ट सेव करें',searchProduct:'प्रोडक्ट, SKU, बारकोड या HSN खोजें…',product:'प्रोडक्ट',price:'कीमत',stock:'स्टॉक',noProducts:'कोई प्रोडक्ट नहीं मिला।',noSku:'SKU नहीं',gstIncluded:'GST शामिल',gstExtra:'GST अतिरिक्त',inStock:'स्टॉक में',removeProductConfirm:'क्या इस प्रोडक्ट को हटाना है? पुराने बिलों में जानकारी सुरक्षित रहेगी।',
  inventoryKicker:'इन्वेंटरी',inventoryTitle:'भरोसेमंद स्टॉक।',inventorySub:'ओनर के लिए सुरक्षित स्टॉक इन/आउट और स्थायी मूवमेंट हिस्ट्री। बिक्री से स्टॉक अपने आप कम होता रहेगा।',ownerControl:'ओनर कंट्रोल',adjustStock:'स्टॉक बदलें',stockIn:'स्टॉक इन',stockOut:'स्टॉक आउट',quantity:'मात्रा',reasonNote:'कारण / नोट',reasonPlaceholder:'नई खरीद, खराब सामान…',addStock:'स्टॉक जोड़ें',removeStock:'स्टॉक घटाएं',updating:'अपडेट हो रहा है…',selectProductAdjust:'स्टॉक बदलने के लिए प्रोडक्ट चुनें।',movementHistory:'मूवमेंट हिस्ट्री',latestStockActivity:'हाल की स्टॉक गतिविधि',type:'प्रकार',change:'बदलाव',stockAfter:'बाद का स्टॉक',note:'नोट',time:'समय',noMovements:'अभी कोई स्टॉक मूवमेंट नहीं है।',searchProductSkuBarcode:'प्रोडक्ट, SKU या बारकोड खोजें…',noSkuBarcode:'SKU / बारकोड नहीं',
  invoicesKicker:'बिल',invoicesTitle:'बिल हिस्ट्री।',invoicesSub:'किसी भी बिल को खोलकर विवरण देखें या 58mm, 80mm या A4 में प्रिंट करें।',payment:'भुगतान',total:'कुल',due:'बकाया',noBills:'अभी कोई बिल नहीं है।',walkInCustomer:'वॉक-इन ग्राहक',viewPrint:'देखें / प्रिंट करें',
  duesKicker:'बकाया और भुगतान',duesTitle:'जो बाकी है, उसे वसूल करें।',duesSub:'मूल बिल बदले बिना बाद का या आंशिक भुगतान दर्ज करें।',totalOutstanding:'कुल बकाया राशि',acrossOpenInvoices:'सभी खुले बिलों में',openBills:'लंबित बिल',invoicesPending:'जिन बिलों में राशि बाकी है',customersWithDues:'जिन ग्राहकों का बकाया है',collection:'भुगतान संग्रह',ownerOnly:'केवल ओनर',protectedByDatabase:'डेटाबेस अनुमति से सुरक्षित',openDues:'खुला बकाया',pendingInvoices:'लंबित बिल',refresh:'रीफ्रेश करें',refreshing:'रीफ्रेश हो रहा है…',loadingOutstanding:'बकाया बिल लोड हो रहे हैं…',nothingDue:'अभी कोई बकाया नहीं है।',allPaid:'सभी योग्य बिल पूरी तरह भुगतान किए गए हैं।',receivePayment:'भुगतान प्राप्त करें',recordPayment:'भुगतान दर्ज करें',selectInvoice:'बिल चुनें',choosePendingInvoice:'बाईं ओर से लंबित बिल चुनें और नकद, UPI, कार्ड या अन्य भुगतान दर्ज करें।',dueNow:'अभी बकाया',amount:'राशि',paymentMethod:'भुगतान तरीका',optional:'वैकल्पिक',notePlaceholder:'रेफरेंस, कलेक्शन नोट आदि',recording:'दर्ज हो रहा है…',openInvoice:'बिल खोलें',enterValidPayment:'सही भुगतान राशि दर्ज करें।',paymentRecorded:'भुगतान दर्ज हो गया।',stillDue:'अभी बाकी है।',invoiceFullyPaid:'बिल का पूरा भुगतान हो गया।',
  reportsKicker:'रिपोर्ट्स',reportsTitle:'जानें आपके बिज़नेस में क्या चल रहा है।',reportsSub:'बिक्री, कलेक्शन, GST, प्रोडक्ट, स्टाफ गतिविधि और स्टॉक संकेत एक जगह।',days:'दिन',sales:'बिक्री',collected:'प्राप्त राशि',moneyReceived:'मिली हुई राशि',dueInRange:'इस अवधि के बिलों से',averageBill:'औसत बिल',averageInvoiceValue:'औसत बिल मूल्य',gstSummary:'GST सारांश',taxView:'इस अवधि का टैक्स विवरण',cancelledExcluded:'रद्द और रिफंड किए गए बिल शामिल नहीं हैं।',totalGst:'कुल GST',taxableSales:'कर योग्य बिक्री',totalTax:'कुल टैक्स',salesTrend:'बिक्री ट्रेंड',dailySales:'दैनिक बिक्री',noSalesPeriod:'इस अवधि में कोई बिक्री नहीं हुई।',payments:'भुगतान',paymentMix:'भुगतान विभाजन',noPaymentData:'भुगतान डेटा नहीं है।',topSellers:'सबसे ज्यादा बिकने वाले',noProductSales:'अभी प्रोडक्ट बिक्री नहीं है।',sold:'बिके',staffCreatedBills:'स्टाफ द्वारा बनाए बिल',noStaffBills:'इस अवधि में स्टाफ द्वारा कोई बिल नहीं बनाया गया।',needsAttention:'ध्यान जरूरी',stockHealthy:'स्टॉक स्तर ठीक हैं।',alertAt:'अलर्ट स्तर',
  settingsKicker:'बिज़नेस सेटिंग्स',settingsTitle:'एक बार सेट करें। बिलिंग तेज करें।',settingsSub:'बिज़नेस पहचान, भाषा, बिल व्यवहार और डिफॉल्ट प्रिंटर एक जगह।',businessProfile:'बिज़नेस प्रोफाइल',businessProfileSub:'यह जानकारी बिल और रसीद पर दिखाई देती है।',businessName:'बिज़नेस नाम',city:'शहर',pincode:'पिनकोड',languageBilling:'भाषा और बिलिंग',languageBillingSub:'काम की भाषा और काउंटर डिफॉल्ट चुनें।',language:'भाषा',invoicePrefix:'बिल प्रीफिक्स',defaultPayment:'डिफॉल्ट भुगतान',printerReceipt:'प्रिंटर और रसीद',printerReceiptSub:'Brandspire POS 2-inch, 3-inch और A4 लेआउट सपोर्ट करता है।',thermalReceipt58:'58mm थर्मल रसीद',thermalReceipt80:'80mm थर्मल रसीद',fullPageGstInvoice:'फुल-पेज GST बिल',printCopies:'प्रिंट कॉपी',showGstinReceipt:'रसीद पर GSTIN दिखाएं',recommendedGst:'GST बिज़नेस के लिए सुझाया गया',allowNegativeStock:'निगेटिव स्टॉक की अनुमति',saferInventory:'सुरक्षित इन्वेंटरी के लिए बंद रखें',receiptHeader:'रसीद हेडर',receiptFooter:'रसीद फुटर',staffBillingPolicy:'स्टाफ बिलिंग नीति',staffBillingPolicySub:'स्टाफ सीमित रहेगा। चाहें तो सीमित प्रतिशत डिस्काउंट की अनुमति दें।',allowStaffDiscount:'स्टाफ डिस्काउंट की अनुमति',backendPolicy:'यह सीमा बैकएंड बिलिंग में लागू होगी।',maximumPercent:'अधिकतम %',readySave:'सेव करने के लिए तैयार?',changesBusinessOnly:'बदलाव केवल इसी बिज़नेस पर लागू होंगे।',saveSettings:'सेटिंग्स सेव करें',settingsSaved:'सेटिंग्स सेव हो गईं। भाषा पूरे वर्कस्पेस में लागू होगी।',
  staffKicker:'टीम एक्सेस',staffTitle:'स्टाफ, बिल्कुल सरल।',staffSub:'ओनर लॉगिन शेयर किए बिना अलग काउंटर अकाउंट बनाएं और एक्सेस नियंत्रित करें।',activeStaff:'सक्रिय स्टाफ',addStaff:'स्टाफ जोड़ें',addStaffSub:'स्टाफ केवल ग्राहक जोड़ सकता है, प्रोडक्ट जोड़ सकता है और बिल बना सकता है।',staffName:'स्टाफ नाम',mobileNumber:'मोबाइल नंबर',temporaryPassword:'अस्थायी पासवर्ड',minimum8:'कम से कम 8 अक्षर',createStaffAccount:'स्टाफ अकाउंट बनाएं',creatingAccount:'अकाउंट बन रहा है…',staffPermissionBoundary:'स्टाफ अनुमति सीमा',noDeleteSettingsSubscription:'डिलीट / सेटिंग्स / सब्सक्रिप्शन नहीं',yourStaff:'आपका स्टाफ',yourStaffSub:'बिज़नेस हिस्ट्री हटाए बिना तुरंत एक्सेस बंद करें।',noStaffAccounts:'अभी कोई स्टाफ अकाउंट नहीं है।',noPhoneAdded:'फोन नहीं जोड़ा गया',active:'सक्रिय',inactive:'निष्क्रिय',resetPassword:'पासवर्ड रीसेट',deactivate:'निष्क्रिय करें',activate:'सक्रिय करें',staffCreatedSuccess:'स्टाफ अकाउंट बन गया। अस्थायी पासवर्ड सुरक्षित तरीके से साझा करें।',
  counterKickerOwner:'तेज बिलिंग',counterKickerStaff:'स्टाफ काउंटर',counterOwnerTitle:'बिल बनाएं।',counterStaffTitle:'नया बिल बनाएं।',counterSub:'प्रोडक्ट खोजें, भुगतान लें और बिल पूरा करें। प्रिंट से पहले बिल सेव होता है।',searchFocused:'सर्च फोकस में रहता है',billCreated:'बिल बन गया',stockUpdated:'स्टॉक अपने आप अपडेट हुआ',newBill:'नया बिल',scanSearch:'बारकोड / SKU स्कैन करें या प्रोडक्ट खोजें…',noMatchingProducts:'मिलता हुआ प्रोडक्ट नहीं मिला।',currentBill:'मौजूदा बिल',item:'आइटम',items:'आइटम',startProduct:'प्रोडक्ट से शुरू करें।',searchTapAdd:'बाईं ओर खोजें और जोड़ने के लिए टैप करें।',discount:'डिस्काउंट',percentage:'प्रतिशत %',flat:'फ्लैट ₹',value:'मूल्य',ownerDiscountLimit:'ओनर सीमा',discountOwnerOnly:'इस बिज़नेस में डिस्काउंट केवल ओनर दे सकता है।',amountPaid:'भुगतान राशि',amountPaidHint:'खाली = पूरा भुगतान; Credit = ₹0',taxable:'कर योग्य',creatingBill:'बिल बन रहा है…',transactionSavedFirst:'लेन-देन पहले सेव होता है। प्रिंट फेल होने पर भी बिल सुरक्षित रहेगा।',
  staffCustomersKicker:'ग्राहक · स्टाफ',staffCustomersTitle:'ग्राहक जोड़ें।',staffCustomersSub:'काउंटर पर जितनी जानकारी चाहिए उतनी ही भरें। मैनेजमेंट और डिलीट ओनर के पास रहेगा।',staffCustomerNewSub:'शुरू करने के लिए नाम काफी है।',staffProductsKicker:'प्रोडक्ट · स्टाफ',staffProductsTitle:'बिक्री वाला प्रोडक्ट जोड़ें।',staffProductsSub:'स्टाफ बिलिंग के लिए प्रोडक्ट बना सकता है। एडिट, डिलीट और संवेदनशील मैनेजमेंट ओनर-ओनली हैं।',staffProductNewSub:'तेज रखें: नाम, बिक्री मूल्य, GST और स्टॉक।',noStateAdded:'राज्य नहीं जोड़ा गया',noCode:'कोड नहीं',
  staffFastCounter:'तेज काउंटर',staffReadyTitle:'अगले ग्राहक के लिए तैयार।',staffPausedTitle:'बिज़नेस एक्सेस रुका हुआ है।',staffReadySub:'स्टाफ की जरूरत की हर चीज एक टैप में। पहले बिल बनाएं; ग्राहक और प्रोडक्ट जोड़ना आसान रखें।',staffPausedSub:'ओनर का सब्सक्रिप्शन सक्रिय नहीं है। ओनर से Brandspire Team से संपर्क करने को कहें।',staffCustomerHelp:'ग्राहक जल्दी जोड़ें। स्टाफ जोड़ और खोज सकता है, डिलीट नहीं।',staffProductHelp:'GST, कीमत और शुरुआती स्टॉक के साथ प्रोडक्ट जोड़ें।',staffRule:'स्टाफ = काम करे। ओनर = मैनेज करे। डिलीट, सेटिंग्स और सब्सक्रिप्शन ओनर-ओनली हैं।',
  noBillsDashboard:'अभी कोई बिल नहीं है। पहला बिल यहां दिखाई देगा।',searchTakeFinish:'प्रोडक्ट खोजें, भुगतान लें, बिल पूरा करें।',saveCustomerDues:'ग्राहक की जानकारी और बकाया सेव करें।',addStockGstPrice:'स्टॉक, GST और बिक्री मूल्य जोड़ें।',
  date:'दिनांक',invoiceKicker:'बिल',back:'वापस',downloadPdf:'PDF डाउनलोड करें',sharePdf:'PDF शेयर करें',collectPayment:'भुगतान लें',cancelledInvoice:'रद्द किया गया बिल',noReasonRecorded:'कारण दर्ज नहीं है',noPaymentMethod:'भुगतान तरीका नहीं',created:'बनाया गया',status:'स्थिति',from:'विक्रेता',billTo:'बिल प्राप्तकर्ता',businessAddressMissing:'बिज़नेस पता नहीं जोड़ा गया',noAddressShort:'पता नहीं',qty:'मात्रा',rate:'दर',subtotal:'उप-योग',grandTotal:'कुल राशि',paid:'भुगतान हुआ',paymentHistory:'भुगतान इतिहास',moneyReceivedHistory:'प्राप्त राशि',noPaymentRecorded:'इस बिल पर कोई भुगतान दर्ज नहीं है।',cancelInvoiceTitle:'यह बिल रद्द करें',cancelSafeCopy:'रद्द करने पर बिक्री वाला स्टॉक वापस जुड़ जाएगा और unpaid customer due हट जाएगा।',cancelPaidCopy:'इस बिल पर भुगतान मिल चुका है। इसे रद्द करने के बजाय refund/credit-note flow उपयोग करें।',cancelInvoice:'बिल रद्द करें',cancelReasonPlaceholder:'रद्द करने का कारण (जरूरी)',keepInvoice:'बिल रखें',confirmCancellation:'रद्द करने की पुष्टि करें',cancelling:'रद्द हो रहा है…',printFormat:'प्रिंट फॉर्मेट',printTitle:'जैसा चाहिए वैसा प्रिंट करें।',printSub:'58mm, 80mm या A4 चुनें। Desktop installed printer driver उपयोग करता है; Android direct Bluetooth/USB printing native printer bridge से होगी।',thermal2:'2-inch thermal',thermal3:'3-inch thermal',a4Invoice:'A4 बिल',print:'प्रिंट',pdfSharing:'PDF शेयरिंग',shareNote:'Supported phone/tablet पर Share PDF native share sheet खोलता है जिससे WhatsApp या अन्य apps पर भेज सकते हैं।',
  subscriptionTrialFallback:'Brandspire POS की फ्री अवधि का आनंद लें। तेज बिलिंग और आसान बिज़नेस मैनेजमेंट आज़माएं।',subscriptionActiveFallback:'आपका Brandspire POS एक्सेस सक्रिय है। बिना रुकावट बिलिंग जारी रखें।',subscriptionBlockedFallback:'आपका Brandspire POS एक्सेस सीमित है। सहायता के लिए Brandspire Team से संपर्क करें।',trialValidUntil:'ट्रायल मान्य है',accessValidUntil:'एक्सेस मान्य है',free:'फ्री',live:'सक्रिय'
};

const hinglish: Messages = {
  ...en,
  dashboard:'Dashboard',createBill:'Bill Banao',customers:'Customers',products:'Products',inventory:'Inventory',invoices:'Bills',dues:'Baaki & Payments',reports:'Reports',staff:'Staff',settings:'Settings',logout:'Logout',
  ownerWorkspace:'Owner workspace',staffWorkspace:'Staff workspace',secureWorkspace:'Secure workspace',softwareSolutions:'Growing businesses ke liye software solutions',
  todaySales:'Aaj ki Sales',todayBills:'Aaj ke Bills',lowStock:'Low Stock',outstanding:'Baaki Amount',recentBills:'Recent Bills',addCustomer:'Customer Add Karo',addProduct:'Product Add Karo',quickActions:'Quick Actions',subscription:'Subscription',dashboardGreeting:'Aapka swagat hai.',dashboardSub:'Business ki zaroori cheezein, bina extra clutter ke.',runCounter:'Counter aur fast chalao',latestActivity:'Latest activity',viewAll:'Sab dekho',salesHint:'Completed bills se live',billsHint:'Aaj banaye gaye bills',duesHint:'Customer ka baaki amount',stockHint:'Stock jisko attention chahiye',
  loadingBrandspire:'Brandspire POS load ho raha hai',preparingWorkspace:'Aapka workspace ready ho raha hai',checkingAccount:'Account check ho raha hai',loadingBusiness:'Business load ho raha hai',syncingSettings:'Settings sync ho rahi hain',almostReady:'Bas ready hai',
  assist:'Brandspire Assist',offlineHelp:'Offline help',assistIntro:'Brandspire POS use karne ke baare mein poochho. Ye help bina internet bhi chalti hai.',assistPlaceholder:'Billing, printer, customer ke baare mein poochho…',assistNoMatch:'Ye question exact match nahi hua. Billing, printer, customer, product, payment, Staff ya settings ke baare mein poochho.',close:'Close',clear:'Clear',
  helpBillQ:'Bill kaise banao?',helpPrinterQ:'Bill print kaise karu?',helpDueQ:'Pending payment kaise receive karu?',helpCustomerQ:'Customer kaise add karu?',
  customersKicker:'CUSTOMERS',customersTitle:'Jin logon ko aap sell karte ho.',customersSub:'Customer details aur baaki amount ek clean jagah par rakho.',newCustomer:'Naya customer',newCustomerSub:'Sirf name required hai. Baaki details zarurat par add karo.',name:'Name',phone:'Phone',email:'Email',state:'State',address:'Address',cancel:'Cancel',saveCustomer:'Customer Save Karo',saving:'Save ho raha hai…',searchCustomer:'Name, phone, email ya GSTIN search karo…',customer:'Customer',contact:'Contact',noCustomers:'Koi customer nahi mila.',noAddress:'Address add nahi hai',remove:'Remove',removeCustomerConfirm:'Is customer ko remove karein? Purani history safe rahegi.',
  productsKicker:'PRODUCTS',productsTitle:'Aapka selling catalog.',productsSub:'Fast counter ke liye price, GST aur stock ek jagah.',newProduct:'Naya product',newProductSub:'Abhi essential details add karo. Baad mein catalog expand kar sakte ho.',productName:'Product Name',sellingPrice:'Selling Price ₹',purchasePrice:'Purchase Price ₹',openingStock:'Opening Stock',gstRate:'GST Rate',unit:'Unit',lowStockAlert:'Low Stock Alert At',priceIncludesGst:'Selling price mein GST already included hai',saveProduct:'Product Save Karo',searchProduct:'Product, SKU, barcode ya HSN search karo…',product:'Product',price:'Price',stock:'Stock',noProducts:'Koi product nahi mila.',noSku:'No SKU',gstIncluded:'GST included',gstExtra:'GST extra',inStock:'In stock',removeProductConfirm:'Is product ko remove karein? Purane bills mein product snapshot safe rahega.',
  inventoryKicker:'INVENTORY',inventoryTitle:'Stock jiske numbers clear rahen.',inventorySub:'Owner-only stock in/out aur permanent movement history. Sales se stock automatically kam hota rahega.',ownerControl:'OWNER CONTROL',adjustStock:'Stock adjust karo',stockIn:'Stock In',stockOut:'Stock Out',quantity:'Quantity',reasonNote:'Reason / Note',reasonPlaceholder:'Purchase received, damaged item…',addStock:'Stock Add Karo',removeStock:'Stock Remove Karo',updating:'Update ho raha hai…',selectProductAdjust:'Stock adjust karne ke liye product select karo.',movementHistory:'MOVEMENT HISTORY',latestStockActivity:'Latest stock activity',type:'Type',change:'Change',stockAfter:'Stock After',note:'Note',time:'Time',noMovements:'Abhi koi stock movement nahi hai.',searchProductSkuBarcode:'Product, SKU ya barcode search karo…',noSkuBarcode:'No SKU / barcode',
  invoicesKicker:'BILLS',invoicesTitle:'Bill history.',invoicesSub:'Koi bhi bill open karke details dekho ya 58mm, 80mm ya A4 mein print karo.',payment:'Payment',total:'Total',due:'Due',noBills:'Abhi koi bill nahi hai.',walkInCustomer:'Walk-in Customer',viewPrint:'View / Print',
  duesKicker:'BAAKI & PAYMENTS',duesTitle:'Jo pending hai, usko collect karo.',duesSub:'Original bill change kiye bina later ya partial payment record karo.',totalOutstanding:'Total Baaki Amount',acrossOpenInvoices:'Saare open invoices mein',openBills:'Pending Bills',invoicesPending:'Jin invoices mein amount pending hai',customersWithDues:'Jinke current dues hain',collection:'Payment Collection',ownerOnly:'Sirf Owner',protectedByDatabase:'Database authorization se protected',openDues:'OPEN DUES',pendingInvoices:'Pending Invoices',refresh:'Refresh Karo',refreshing:'Refresh ho raha hai…',loadingOutstanding:'Pending bills load ho rahe hain…',nothingDue:'Abhi koi payment pending nahi hai.',allPaid:'Saare eligible invoices fully paid hain.',receivePayment:'PAYMENT RECEIVE KARO',recordPayment:'Payment Record Karo',selectInvoice:'Invoice Select Karo',choosePendingInvoice:'Left side se pending invoice select karo aur Cash, UPI, Card ya Other payment record karo.',dueNow:'Abhi Due',amount:'Amount',paymentMethod:'Payment Method',optional:'optional',notePlaceholder:'Reference, collection note, etc.',recording:'Record ho raha hai…',openInvoice:'Invoice Open Karo',enterValidPayment:'Valid payment amount enter karo.',paymentRecorded:'Payment record ho gaya.',stillDue:'abhi baaki hai.',invoiceFullyPaid:'Invoice fully paid ho gaya.',
  reportsKicker:'REPORTS',reportsTitle:'Samjho business mein kya move kar raha hai.',reportsSub:'Sales, collections, GST, products, Staff activity aur stock signals ek clean view mein.',days:'days',sales:'Sales',collected:'Collected',moneyReceived:'Receive hua paisa',dueInRange:'Is range ke bills se',averageBill:'Average Bill',averageInvoiceValue:'Average invoice value',gstSummary:'GST SUMMARY',taxView:'Is period ka tax view',cancelledExcluded:'Cancelled aur refunded invoices include nahi hain.',totalGst:'Total GST',taxableSales:'Taxable Sales',totalTax:'Total Tax',salesTrend:'SALES TREND',dailySales:'Daily Sales',noSalesPeriod:'Is period mein sales nahi hai.',payments:'PAYMENTS',paymentMix:'Payment Mix',noPaymentData:'Payment data nahi hai.',topSellers:'Top Sellers',noProductSales:'Abhi product sales nahi hai.',sold:'sold',staffCreatedBills:'Staff-created Bills',noStaffBills:'Is period mein Staff-created bills nahi hain.',needsAttention:'Attention Chahiye',stockHealthy:'Stock levels healthy lag rahe hain.',alertAt:'Alert at',
  settingsKicker:'BUSINESS SETTINGS',settingsTitle:'Ek baar set karo. Billing fast rakho.',settingsSub:'Business identity, language, invoice behaviour aur default printer ek clean jagah par.',businessProfile:'Business Profile',businessProfileSub:'Ye information invoices aur receipts par dikhegi.',businessName:'Business Name',city:'City',pincode:'Pincode',languageBilling:'Language & Billing',languageBillingSub:'Natural working language aur counter defaults choose karo.',language:'Language',invoicePrefix:'Invoice Prefix',defaultPayment:'Default Payment',printerReceipt:'Printer & Receipt',printerReceiptSub:'Brandspire POS 2-inch, 3-inch aur A4 layouts support karta hai.',thermalReceipt58:'58mm thermal receipt',thermalReceipt80:'80mm thermal receipt',fullPageGstInvoice:'Full-page GST invoice',printCopies:'Print Copies',showGstinReceipt:'Receipt par GSTIN dikhao',recommendedGst:'GST business ke liye recommended',allowNegativeStock:'Negative stock allow karo',saferInventory:'Safer inventory ke liye off rakho',receiptHeader:'Receipt Header',receiptFooter:'Receipt Footer',staffBillingPolicy:'Staff Billing Policy',staffBillingPolicySub:'Staff restricted rahega. Aap limited percentage discount optionally allow kar sakte ho.',allowStaffDiscount:'Staff discount allow karo',backendPolicy:'Ye policy backend billing engine enforce karega.',maximumPercent:'Maximum %',readySave:'Save karne ke liye ready?',changesBusinessOnly:'Changes sirf is business par apply honge.',saveSettings:'Settings Save Karo',settingsSaved:'Settings save ho gayi. Language poore workspace mein apply hogi.',
  staffKicker:'TEAM ACCESS',staffTitle:'Staff, simple rakho.',staffSub:'Owner login share kiye bina individual counter accounts banao aur access control karo.',activeStaff:'active staff',addStaff:'Staff Add Karo',addStaffSub:'Staff sirf customer add, product add aur bill create kar sakta hai.',staffName:'Staff Name',mobileNumber:'Mobile Number',temporaryPassword:'Temporary Password',minimum8:'Minimum 8 characters',createStaffAccount:'Staff Account Banao',creatingAccount:'Account ban raha hai…',staffPermissionBoundary:'Staff permission boundary',noDeleteSettingsSubscription:'Delete / settings / subscription nahi',yourStaff:'Aapka Staff',yourStaffSub:'Business history delete kiye bina access instantly deactivate karo.',noStaffAccounts:'Abhi koi Staff account nahi hai.',noPhoneAdded:'Phone add nahi hai',active:'Active',inactive:'Inactive',resetPassword:'Password Reset',deactivate:'Deactivate',activate:'Activate',staffCreatedSuccess:'Staff account ban gaya. Temporary password securely share karo.',
  counterKickerOwner:'FAST BILLING',counterKickerStaff:'STAFF COUNTER',counterOwnerTitle:'Bill banao.',counterStaffTitle:'Naya bill banao.',counterSub:'Product search karo, payment lo aur bill finish karo. Printing se pehle invoice save hota hai.',searchFocused:'Search focused rehta hai',billCreated:'BILL CREATED',stockUpdated:'stock automatically update hua',newBill:'New Bill',scanSearch:'Barcode / SKU scan karo ya product search karo…',noMatchingProducts:'Matching product nahi mila.',currentBill:'CURRENT BILL',item:'item',items:'items',startProduct:'Product se start karo.',searchTapAdd:'Left side search karo aur add karne ke liye tap karo.',discount:'Discount',percentage:'Percentage %',flat:'Flat ₹',value:'Value',ownerDiscountLimit:'Owner limit',discountOwnerOnly:'Is business mein discount Owner-only hai.',amountPaid:'Amount Paid',amountPaidHint:'blank = full payment; Credit = ₹0',taxable:'Taxable',creatingBill:'Bill ban raha hai…',transactionSavedFirst:'Transaction pehle save hota hai. Printing fail ho to bhi bill safe rahega.',
  staffCustomersKicker:'CUSTOMERS · STAFF',staffCustomersTitle:'Customer add karo.',staffCustomersSub:'Counter par sirf needed details rakho. Management aur delete Owner ke paas rahega.',staffCustomerNewSub:'Start karne ke liye name enough hai.',staffProductsKicker:'PRODUCTS · STAFF',staffProductsTitle:'Sellable product add karo.',staffProductsSub:'Staff billing ke liye products create kar sakta hai. Edit, delete aur sensitive management Owner-only hai.',staffProductNewSub:'Quick rakho: name, selling price, GST aur stock.',noStateAdded:'State add nahi hai',noCode:'No code',
  staffFastCounter:'FAST COUNTER',staffReadyTitle:'Next customer ke liye ready.',staffPausedTitle:'Business access abhi paused hai.',staffReadySub:'Staff ko jo chahiye sab one tap mein. Bill pehle banao; customer aur product setup simple rakho.',staffPausedSub:'Owner ka subscription active nahi hai. Owner se Brandspire Team ko contact karne bolo.',staffCustomerHelp:'Customer jaldi add karo. Staff add/search kar sakta hai, delete nahi.',staffProductHelp:'GST, price aur opening stock ke saath product add karo.',staffRule:'Staff = operate. Owner = manage. Delete, settings aur subscription Owner-only hain.',
  noBillsDashboard:'Abhi koi bill nahi hai. Pehla bill yahan dikhega.',searchTakeFinish:'Products search karo, payment lo, finish karo.',saveCustomerDues:'Customer details aur dues save karo.',addStockGstPrice:'Stock, GST aur selling price add karo.',
  date:'Date',invoiceKicker:'INVOICE',back:'Back',downloadPdf:'PDF Download Karo',sharePdf:'PDF Share Karo',collectPayment:'Payment Collect Karo',cancelledInvoice:'Cancelled Invoice',noReasonRecorded:'Reason record nahi hai',noPaymentMethod:'Payment method nahi hai',created:'Created',status:'Status',from:'FROM',billTo:'BILL TO',businessAddressMissing:'Business address add nahi hai',noAddressShort:'No address',qty:'Qty',rate:'Rate',subtotal:'Subtotal',grandTotal:'Grand Total',paid:'Paid',paymentHistory:'PAYMENT HISTORY',moneyReceivedHistory:'Receive hua paisa',noPaymentRecorded:'Is invoice par koi payment record nahi hai.',cancelInvoiceTitle:'Ye invoice cancel karo',cancelSafeCopy:'Cancellation sold stock restore karta hai aur unpaid customer due remove karta hai.',cancelPaidCopy:'Is invoice par payment capture ho chuka hai. Cancel ki jagah refund/credit-note flow use karo.',cancelInvoice:'Invoice Cancel Karo',cancelReasonPlaceholder:'Cancellation ka reason (required)',keepInvoice:'Invoice Rakho',confirmCancellation:'Cancellation Confirm Karo',cancelling:'Cancel ho raha hai…',printFormat:'PRINT FORMAT',printTitle:'Jaisa chahiye waisa print karo.',printSub:'58mm, 80mm ya A4 choose karo. Desktop installed printer driver use karta hai; Android direct Bluetooth/USB printing native printer bridge use karegi.',thermal2:'2-inch thermal',thermal3:'3-inch thermal',a4Invoice:'A4 Invoice',print:'Print',pdfSharing:'PDF Sharing',shareNote:'Supported phone/tablet par Share PDF native share sheet open karta hai jisse WhatsApp ya other apps par bhej sakte ho.',
  subscriptionTrialFallback:'Brandspire POS free session enjoy karo. Faster billing aur simple business management explore karo.',subscriptionActiveFallback:'Aapka Brandspire POS access active hai. Billing without interruption continue karo.',subscriptionBlockedFallback:'Aapka Brandspire POS access restricted hai. Help ke liye Brandspire Team ko contact karo.',trialValidUntil:'Trial valid until',accessValidUntil:'Access valid until',free:'FREE',live:'LIVE'
};

const messages: Record<PosLanguage, Messages> = { en, hi, hinglish };

export function posText(language: PosLanguage): Messages {
  return messages[language] ?? en;
}

export function posLanguageLabel(language: PosLanguage) {
  return language === 'hi' ? 'हिंदी' : language === 'hinglish' ? 'Hinglish' : 'English';
}

export function localizedStatus(language: PosLanguage, status: string) {
  const normalized = status.replaceAll('_', ' ');
  const hiMap: Record<string,string> = { PAID:'भुगतान पूरा', PENDING:'लंबित', PARTIALLY_PAID:'आंशिक भुगतान', CANCELLED:'रद्द', REFUNDED:'रिफंड', ACTIVE:'सक्रिय', TRIAL:'ट्रायल', GRACE_PERIOD:'ग्रेस अवधि', EXPIRED:'समाप्त', SUSPENDED:'निलंबित' };
  const hgMap: Record<string,string> = { PAID:'Paid', PENDING:'Pending', PARTIALLY_PAID:'Partially Paid', CANCELLED:'Cancelled', REFUNDED:'Refunded', ACTIVE:'Active', TRIAL:'Trial', GRACE_PERIOD:'Grace Period', EXPIRED:'Expired', SUSPENDED:'Suspended' };
  if (language === 'hi') return hiMap[status] ?? normalized;
  if (language === 'hinglish') return hgMap[status] ?? normalized;
  return normalized;
}
